homeassistant:
  name: Åvägen

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  time_zone: !secret timezone_home
  unit_system: metric

  # Everything important is here
  packages: !include_dir_named packages

default_config:
discovery:
frontend:
  themes: !include_dir_merge_named themes
recorder:
  db_url: mysql://hass:hass@db:3306/hass?charset=utf8
logger:
  default: info
  logs:
    homeassistant.components.http.view: warn
influxdb:
  host: influx
  username: hass
  password: hass
  database: hass

homekit:
  ip_address: !secret host_ip
  auto_start: false
  filter:
    include_domains:
      - light
      - switch

http:
  # mydomain.com:443 - proxied by nginx to port 8123
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret proxy_hosts

cloud:

stream:

python_script:

hacs:
  token: !secret hacs_token

lovelace_gen:

automation:
  - alias: Hallampa på
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.framdorr
      to: "on"
    condition:
      condition: state
      entity_id: switch.tod_dark
      state: "on"
    action:
      - service: light.turn_on
        entity_id: light.stora_hallen
  - alias: Start homekit
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:05
      - service: homekit.start

browser_mod:
  devices:
    d94309ff-1b8be6a4:
      name: hallen
