homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "hardware/rflink"

    # light.ute_framsidan:
    #   <<: *common
    light.trappbelysning:
      <<: *common
    light.kontor_fonster:
      <<: *common
    light.deko_vardagsrum:
      <<: *common
    light.skotbord:
      <<: *common
    light.bokhylla:
      <<: *common
    # switch.motorvarmare:
    #   <<: *common
    light.koksfonster:
      <<: *common

rflink:
  host: rflink
  port: 2000

light:
  - platform: rflink
    automatic_add: false
    devices:
      # newkaku_0008f252_1:
      #   name: Ute Framsidan
      ab400d_000042_2:
        name: Trappbelysning
      unitec_e1b8_01:
        name: Kontor Fönster
      unitec_e1b8_02:
        name: Deko Vardagsrum
      newkaku_01b029f6_1:
        name: Skötbord
      newkaku_01b029f6_3:
        name: Bokhylla
      newkaku_01b029f7_3:
        name: Köksfönster

# switch:
#   - platform: rflink
#     devices:
#       newkaku_018cf7f6_10:
#         name: Motorvärmare

