homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "lights"
      grouped: &grouped
        hidden: true

    light.sovrum:
      <<: *common
    light.sovrum1:
      <<: *grouped
    light.sovrum2:
      <<: *grouped
    light.sovrum3:
      <<: *grouped
    light.takflakt:
      <<: *common
    light.fasadbelysning:
      <<: *common
    light.ytterbelysning:
      <<: *common
    light.taklampor:
      <<: *common

  customize_glob:
    light.takflakt_*:
      <<: *grouped
    light.fasad_*:
      <<: *grouped


light:
  - platform: group
    name: Sovrum
    entities:
      - light.sovrum1
      - light.sovrum2
      - light.sovrum3

  - platform: group
    name: Takfläkt
    entities:
      - light.takflakt_1
      - light.takflakt_2
      - light.takflakt_3
      - light.takflakt_4

  - platform: group
    name: Fasadbelysning
    entities:
      - light.fasad_1
      - light.fasad_2
      - light.fasad_3
      - light.fasad_4
      - light.fasad_5
      - light.fasad_6
      - light.fasad_7
      - light.fasad_8

  - platform: group
    name: Ytterbelysning
    entities:
      - light.entre
      - light.baksida
      - light.mellangang
      - light.uppfart

  - platform: group
    name: Taklampor
    entities:
      - light.lilla_hallen
      - light.sovrum
      - light.stora_hallen
      - light.takflakt
      - light.taklampa_koket
      - light.taklampa_kontoret
      - light.vardagsrum

circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.taklampa_kontoret
      - light.lilla_hallen
      - light.stora_hallen
      - light.takflakt_1
      - light.takflakt_2
      - light.takflakt_3
      - light.takflakt_4
      - light.vardagsrum
      - light.taklampa_koket
